security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 10
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
           user_providers:
               entity: {class: App\Entity\User, property: mail}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true
        login:
            pattern: ^/api/login$
            stateless: true
            anonymous: true
            json_login:
                check_path:               user_login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:  ^/api/users$
            stateless: true
            anonymous: true
        recipes:
            pattern:  ^/api/recipes$
            stateless: true
            anonymous: true
        recipe:
            pattern:  ^/api/recipes/[0-9]+$
            stateless: true
            anonymous: true
        api:
            pattern:   ^/api/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            stateless: true
            anonymous: ~

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }